---
# tasks file for docker

- include: "{{ansible_distribution}}.yml"

- name: Copy daemon.json settings
  template:
    dest: /etc/docker/daemon.json
    src: daemon.json
    mode: 0644
    owner: root
    group: root
    force: no
  notify: restart_docker

- name: Create /etc/docker-compose
  file:
    dest: /etc/docker-compose
    mode: 0755
    state: directory
